name: 👨🏻‍💻 General
description: Create a general issue to improve the SL Design System
labels: ["triage"]
projects: ["projects/2"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
  - type: markdown
    attributes:
      value: "# 👨🏻‍💻 General"
  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the issue here
    validations:
      required: true
